# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PPDemo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PPDemo

  pod 'Alamofire'
  pod 'SnapKit'
  pod 'SDWebImage'

  target 'PPDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
